spring.application.name=Spring MVC
spring.datasource.url=jdbc:h2:mem:product_DB;
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
server.port=8080
spring.h2.console.enabled=true
